local req_err_handling = require 'utils.error_handling'
local Keymap = require('utils.keymap')
Keymap('n', '<leader>q', 'lua vim.lsp.buf.code_action()')
Keymap('n', '<leader>d', 'lua vim.lsp.buf.definition()')
Keymap('n', '<leader>s', 'lua vim.lsp.buf.hover()')
Keymap('n', '<leader>i', 'lua vim.lsp.buf.implementation()')
Keymap('n', '<leader>sh', 'lua vim.lsp.buf.signature_help()')
Keymap('n', '<leader>td', 'lua vim.lsp.buf.type_definition()')
Keymap('n', '<leader>r', 'lua vim.lsp.buf.references()')
Keymap('n', '<leader>ds', 'lua vim.lsp.buf.document_symbol()')
Keymap('n', '<leader>ws', 'lua vim.lsp.buf.workspace_symbol()')
Keymap('n', '<leader>th', ':botright new <Bar> :terminal')
Keymap('n', '<leader>ts', ':botright vnew <Bar> :terminal')
Keymap('n', '<leader>dn', 'lua vim.diagnostic.goto_next()')
Keymap('n', '<leader>dp', 'lua vim.diagnostic.goto_prev()')
